name: sdvae
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pip
  - pip:
    - glob2
    - blobfile
    - lpips
    - diffusers
    - accelerate 
    - mpi4py
    - torch
    - torchvision
    - opencv-python-headless